language: node_js
node_js:
  - "6.10"
  - "4.3"
cache:
  directories:
    - node_modules
script: 
    - npm install -g serverless
    - npm run setup
    - npm run install:dynamodb
    - npm start
    - export AWS_REGION=us-east-2
    - sleep 20
    - npm test
