service: taco-gallery

provider:
  name: aws
  runtime: nodejs4.3


resources:
  Resources:
    TacosDB:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: name
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          -
            AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: TacoGallery

functions:
  saveTaco:
    handler: handler.saveTaco
    events:
      - http:
          path: taco
          method: post
plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  serverless-offline:
    babelOptions:
      presets: ["es2015"]