service: taco-gallery

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-2
  stage: dev


resources:
  Resources:
    TacosDB:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: name
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          -
            AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: TacoGallery

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  saveTaco:
    handler: handler.saveTaco
    events:
      - http:
          path: taco
          method: post


plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-webpack

custom:
  webpackIncludeModules:
    packagePath: './package.json'
  serverless-offline:
    babelOptions:
      presets: ["es2015"]